minecraft_health = {
    "Player": {
        "Default": 20,
        "With Absorption": "Up to 40",
        "With Resistance effect": "Up to 80",
        "With both": "Up to 100"
    },
    "Mobs": {
        "Bat": 6,
        "Bee": 10,
        "Cat": 10,
        "Chicken": 4,
        "Cod": 3,
        "Cow": 10,
        "Dolphin": 10,
        "Donkey": 15,
        "Fox": 10,
        "Horse": "15 - 30",
        "Mooshroom": 10,
        "Mule": 15,
        "Ocelot": 10,
        "Parrot": 6,
        "Pig": 10,
        "Rabbit": 3,
        "Salmon": 3,
        "Sheep": 8,
        "Skeleton Horse": 15,
        "Squid": 10,
        "Tropical Fish": 3,
        "Turtle": 30,
        "Villager": 20,
        "Wandering Trader": 20,
        "Wolf": 8,
        "Zombie Horse": 15
    },
    "Hostile Mobs": {
        "Blaze": 20,
        "Cave Spider": 12,
        "Creeper": 20,
        "Drowned": 20,
        "Elder Guardian": 80,
        "Ender Dragon": 200,
        "Enderman": 40,
        "Endermite": 8,
        "Evoker": 24,
        "Ghast": 10,
        "Guardian": 30,
        "Hoglin": 40,
        "Husk": 20,
        "Illusioner": 32,
        "Magma Cube": "4 - 16",
        "Phantom": 20,
        "Piglin": 16,
        "Piglin Brute": 50,
        "Pillager": 24,
        "Ravager": 100,
        "Shulker": 30,
        "Silverfish": 8,
        "Skeleton": 20,
        "Slime": "1 - 16",
        "Spider": 16,
        "Stray": 20,
        "Vex": 14,
        "Vindicator": 24,
        "Witch": 26,
        "Wither": 300,
        "Wither Skeleton": 20,
        "Zoglin": 40,
        "Zombie": 20,
        "Zombie Villager": 20,
        "Zombified Piglin": 20
    },
    "Passive Mobs": {
        "Iron Golem": 100,
        "Snow Golem": 4
    },
    "Bosses": {
        "Ender Dragon": 200,
        "Wither": 300
    }
}
