from pydantic import BaseModel

# generated by chatGpt
items = {
    270: 'wooden_pickaxe',
    257: 'iron_pickaxe',
    278: 'diamond_pickaxe',
    271: 'wooden_axe',
    258: 'iron_axe',
    265: 'iron_ore',
    266: 'iron_ingot',
    5: 'wooden_planks',
    280: 'stick',
    260: 'apple',
    319: 'raw_porkchop',
    363: 'raw_beef',
    365: 'raw_chicken',
    364: 'raw_mutton',
    320: 'cooked_porkchop',
    364: 'cooked_beef',
    366: 'cooked_chicken',
    365: 'cooked_mutton',
    1: 'stone',
    4: 'cobblestone',
    24: 'sandstone',
    48: 'mossy_cobblestone',
    98: 'stone_bricks',
    98: 'stone_brick_slabs',
    98: 'stone_brick_stairs',
    98: 'stone_brick_walls'
}

foods = {
    260:'apple',
    297:'bread',
    319:'raw_porkchop',
    320:'cooked_porkchop',
    363:'raw_beef',
    364:'cooked_beef',
    365:'raw_chicken',
    366:'cooked_chicken',
    349:'raw_fish',
    350:'cooked_fish',
    349:'raw_salmon',
    350:'cooked_salmon',
    367:'rotten_flesh',
    375:'spider_eye',
    365:'mutton',
    424:'rabbit',
    412:'cooked_rabbit',
    423:'rabbit_stew',
    391:'carrot',
    392:'potato',
    393:'baked_potato',
    394:'poisonous_potato',
    360:'melon_slice',
    322:'golden_apple',
    466:'enchanted_golden_apple',
    357:'cookie',
    375:'pumpkin_pie',
    319:'beetroot',
    413:'beetroot_soup',
    376:'cooked_mutton',
    411:'cooked_cod',
    412:'cooked_salmon',
    425:'sweet_berries',
    376:'honey_bottle',
    677:'glow_berries'
}

weapons = {
    268:'wooden_sword',
    272:'stone_sword',
    267:'iron_sword',
    276:'diamond_sword',
    283:'gold_sword',
    271:'wooden_axe',
    275:'stone_axe',
    258:'iron_axe',
    279:'diamond_axe',
    286:'gold_axe',
    258:'bow',
    261:'bow_arrow',
    346:'fishing_rod',
    359:'shears',
    398:'carrot_on_a_stick',
    443:'warped_fungus_on_a_stick',
    421:'crossbow',
    425:'trident',
    901:'netherite_sword',
    906:'netherite_axe'
}


class EntityStats(BaseModel):
    damage: int
    health: int
    speed: float
    aggressiveness: str

class EntityStats(BaseModel):
    damage: int
    health: int
    speed: float

hostile_entity_stats = {
    "blaze": EntityStats(damage=6, health=20, speed=0),
    "cave_spider": EntityStats(damage=2, health=12, speed=0),
    "creeper": EntityStats(damage=49, health=20, speed=0),
    "drowned": EntityStats(damage=3, health=20, speed=0),
    "elder_guardian": EntityStats(damage=6, health=80, speed=0),
    "ender_dragon": EntityStats(damage=10, health=200, speed=0),
    "enderman": EntityStats(damage=7, health=40, speed=0),
    "endermite": EntityStats(damage=2, health=8, speed=0),
    "evoker": EntityStats(damage=6, health=24, speed=0),
    "ghast": EntityStats(damage=17, health=10, speed=0),
    "guardian": EntityStats(damage=6, health=30, speed=0),
    "hoglin": EntityStats(damage=4, health=40, speed=0),
    "husk": EntityStats(damage=3, health=20, speed=0),
    "illusioner": EntityStats(damage=6, health=32, speed=0),
    "magma_cube": EntityStats(damage=4, health=16, speed=0),
    "phantom": EntityStats(damage=6, health=20, speed=0),
    "piglin": EntityStats(damage=5, health=16, speed=0),
    "piglin_brute": EntityStats(damage=7, health=50, speed=0),
    "pillager": EntityStats(damage=5, health=24, speed=0),
    "ravager": EntityStats(damage=12, health=100, speed=0),
    "shulker": EntityStats(damage=4, health=30, speed=0),
    "silverfish": EntityStats(damage=1, health=8, speed=0),
    "skeleton": EntityStats(damage=4, health=20, speed=0),
    "slime": EntityStats(damage=4, health=16, speed=0),
    "spider": EntityStats(damage=3, health=16, speed=0),
    "stray": EntityStats(damage=4, health=20, speed=0),
    "vex": EntityStats(damage=9, health=14, speed=0),
    "vindicator": EntityStats(damage=7, health=24, speed=0),
    "witch": EntityStats(damage=10, health=26, speed=0),
    "wither": EntityStats(damage=8, health=300, speed=0),
    "wither_skeleton": EntityStats(damage=8, health=20, speed=0),
    "zoglin": EntityStats(damage=2, health=40, speed=0),
    "zombie": EntityStats(damage=3, health=20, speed=0),
    "zombie_villager": EntityStats(damage=3, health=20, speed=0),
    "zombified_piglin": EntityStats(damage=5, health=20, speed=0),
}

hostile_entity_speeds = {
    'zombie': 0.23,
    'skeleton': 0.25,
    'creeper': 0.25,
    'spider': 0.3,
    'enderman': 0.3,
    'witch': 0.25,
    'blaze': 0.23,
    'ghast': 0.0,
    'magma_cube': 0.23,
    'silverfish': 0.3,
    'stray': 0.25,
    'vex': 0.5,
    'vindicator': 0.23,
    'pillager': 0.3
}

for entity, speed in hostile_entity_speeds.items():
    if entity in hostile_entity_stats:
        hostile_entity_stats[entity].speed = speed

neutral_entities_health = {
    "Bat": 6,
    "Bee": 10,
    "Cat": 10,
    "Chicken": 4,
    "Cod": 3,
    "Cow": 10,
    "Dolphin": 10,
    "Donkey": 15,
    "Fox": 10,
    "Horse": 30,
    "Mooshroom": 10,
    "Mule": 15,
    "Ocelot": 10,
    "Parrot": 6,
    "Pig": 10,
    "Rabbit": 3,
    "Salmon": 3,
    "Sheep": 8,
    "Skeleton Horse": 15,
    "Squid": 10,
    "Tropical Fish": 3,
    "Turtle": 30,
    "Villager": 20,
    "Wandering Trader": 20,
    "Wolf": 8,
    "Zombie Horse": 15,
    "Player": 20
}

indexes = {
    'items': items,
    'foods': foods,
    'weapons': weapons,
    'hostiles': hostile_entity_stats,
    "neutrals": neutral_entities_health
}