# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install wheel
        python -m pip install twine
        python -m pip install keyrings.google-artifactregistry-auth
        python -m pip install pytest
        python -m pip install -r requirements.txt
    - name: Test
      run: pytest
    - name: Build package
      env:
        GITHUB_RUN_NUMBER: '${{ github.run_number }}'
      run: python setup.py sdist bdist_wheel
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
    - name: Upload to Artifact Registry
      env:
        GCP_CREDS: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      run: |
        gcloud config set artifacts/repository swarmly-python-repo
        gcloud config set artifacts/location australia-southeast1
        gcloud config set account swarmly-git@rare-ethos-384523.iam.gserviceaccount.com
        echo $GCP_CREDS >> temp.json
        gcloud auth activate-service-account swarmly-git@rare-ethos-384523.iam.gserviceaccount.com --project=rare-ethos-384523 --key-file=temp.json
        rm temp.json
        gcloud artifacts print-settings python > ~/.pypirc
        python -m twine upload --repository swarmly-python-repo dist/*
